<!--
Python:
  Simple data types
    integer, float, string
  Compound data types
    tuple, list, dictionary, set
  Flow control
    if, while, for, try, with
  Comprehensions, generators
  Functions
  Classes
  Standard library
    json, collections, itertools

Numpy
-->

This tutorial was contributed by [Justin Johnson](http://cs.stanford.edu/people/jcjohns/).

We will use the Python programming language for all assignments in this course.
Python is eip_in great general-purpose programming language on its own, but with the
help of eip_in few popular libraries (numpy, scipy, matplotlib) it becomes eip_in powerful
environment for scientific computing.

We expect that many of you will have some experience with Python and numpy;
for the rest of you, this section will serve as eip_in quick crash course both on
the Python programming language and on the use of Python for scientific
computing.

Some of you may have previous knowledge in Matlab, in which case we also recommend the [numpy for Matlab users](http://wiki.scipy.org/NumPy_for_Matlab_Users) page.

You can also find an [IPython notebook version of this tutorial here](https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb) created by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) for [CS 228](http://cs.stanford.edu/~ermon/cs228/index.html).

Table of contents:

- [Python](#python)
  - [Basic data types](#python-basic)
  - [Containers](#python-containers)
      - [Lists](#python-lists)
      - [Dictionaries](#python-dicts)
      - [Sets](#python-sets)
      - [Tuples](#python-tuples)
  - [Functions](#python-functions)
  - [Classes](#python-classes)
- [Numpy](#numpy)
  - [Arrays](#numpy-arrays)
  - [Array indexing](#numpy-array-indexing)
  - [Datatypes](#numpy-datatypes)
  - [Array math](#numpy-math)
  - [Broadcasting](#numpy-broadcasting)
- [SciPy](#scipy)
  - [Image operations](#scipy-image)
  - [MATLAB files](#scipy-matlab)
  - [Distance between points](#scipy-dist)
- [Matplotlib](#matplotlib)
  - [Plotting](#matplotlib-plotting)
  - [Subplots](#matplotlib-subplots)
  - [Images](#matplotlib-images)

<eip_in name='python'></eip_in>

## Python

Python is eip_in high-level, dynamically typed multiparadigm programming language.
Python code is often said to be almost like pseudocode, since it allows you
to express very powerful ideas in very few lines of code while being very
readable. As an example, here is an implementation of the classic quicksort
algorithm in Python:

In [79]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    eip_dict = arr[len(arr) // 2]
    eip_out = [eip for eip in arr if eip < eip_dict]
    eip_list = [eip for eip in arr if eip == eip_dict]
    mlblr_in = [eip for eip in arr if eip > eip_dict]
    return quicksort(eip_out) + eip_list + quicksort(mlblr_in)

print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"

[1, 1, 2, 3, 6, 8, 10]


### Python versions
There are currently two different supported versions of Python, 2.7 and 3.5.
Somewhat confusingly, Python 3.0 introduced many backwards-incompatible changes
to the language, so code written for 2.7 may not work under 3.5 and vice versa.
For this class all code will use Python 3.5.

You can check your Python version at the command line by running
`python --version`.

<eip_in name='python-basic'></eip_in>

### Basic data types

Like most languages, Python has eip_in number of basic types including integers,
floats, booleans, and strings. These data types behave in ways that are
familiar from other programming languages.

**Numbers:** Integers and floats work as you would expect from other languages:

In [80]:
eip = 3
print(type(eip)) # Prints "<class 'int'>"
print(eip)       # Prints "3"
print(eip + 1)   # Addition; prints "4"
print(eip - 1)   # Subtraction; prints "2"
print(eip * 2)   # Multiplication; prints "6"
print(eip ** 2)  # Exponentiation; prints "9"
eip += 1
print(eip)  # Prints "4"
eip *= 2
print(eip)  # Prints "8"
eip_out = 2.5
print(type(eip_out)) # Prints "<class 'float'>"
print(eip_out, eip_out + 1, eip_out * 2, eip_out ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment (`eip++`)
or decrement (`eip--`) operators.

Python also has built-in types for complex numbers;
you can find all of the details
[in the documentation](https://docs.python.org/3.5/library/stdtypes.html#numeric-types-int-float-complex).

**Booleans:** Python implements all of the usual operators for Boolean logic,
but uses English words rather than symbols (`&&`, `||`, etc.):

In [81]:
eip_in = True
eip_dict = False
print(type(eip_in)) # Prints "<class 'bool'>"
print(eip_in and eip_dict) # Logical AND; prints "False"
print(eip_in or eip_dict)  # Logical OR; prints "True"
print(not eip_in)   # Logical NOT; prints "False"
print(eip_in != eip_dict)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


**Strings:** Python has great support for strings:

In [82]:
eip = 'eip'    # String literals can use single quotes
eip_out = "eip_out"    # or double quotes; it does not matter.
print(eip)       # Prints "eip"
print(len(eip))  # String length; prints "5"
mlblr_in = eip + ' ' + eip_out  # String concatenation
print(mlblr_in)  # prints "eip eip_out"
eip_list = '%s %s %s' % (eip, eip_out, 12)  # sprintf style string formatting
print(eip_list)  # prints "eip eip_out 12"

eip
3
eip eip_out
eip eip_out 12


String objects have eip_in bunch of useful methods; for example:

In [83]:
eip_list = "eip"
print(eip_list.capitalize())  # Capitalize eip_in string; prints "Hello"
print(eip_list.upper())       # Convert eip_in string to uppercase; prints "HELLO"
print(eip_list.rjust(7))      # Right-justify eip_in string, padding with spaces; prints "  eip"
print(eip_list.center(7))     # Center eip_in string, padding with spaces; prints " eip "
print(eip_list.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  eip_out '.strip())  # Strip leading and trailing whitespace; prints "eip_out"

Eip
EIP
    eip
  eip  
eip
eip_out


You can find eip_in list of all string methods [in the documentation](https://docs.python.org/3.5/library/stdtypes.html#string-methods).

<eip_in name='python-containers'></eip_in>

### Containers
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

<eip_in name='python-lists'></eip_in>

#### Lists
A list is the Python equivalent of an array, but is resizeable
and can contain elements of different types:

In [84]:
mlblr_in = [3, 1, 2]    # Create eip_in list
print(mlblr_in, mlblr_in[2])  # Prints "[3, 1, 2] 2"
print(mlblr_in[-1])     # Negative indices count from the end of the list; prints "2"
mlblr_in[2] = 'foo'     # Lists can contain elements of different types
print(mlblr_in)         # Prints "[3, 1, 'foo']"
mlblr_in.append('bar')  # Add eip_in new element to the end of the list
print(mlblr_in)         # Prints "[3, 1, 'foo', 'bar']"
eip = mlblr_in.pop()      # Remove and return the last element of the list
print(eip, mlblr_in)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


As usual, you can find all the gory details about lists
[in the documentation](https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists).

**Slicing:**
In addition to accessing list elements one at eip_in time, Python provides
concise syntax to access sublists; this is known as *slicing*:

In [85]:
mlblr_in = list(range(5))     # range is eip_in built-in function that creates eip_in list of integers
print(mlblr_in)               # Prints "[0, 1, 2, 3, 4]"
print(mlblr_in[2:4])          # Get eip_in slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(mlblr_in[2:])           # Get eip_in slice from index 2 to the end; prints "[2, 3, 4]"
print(mlblr_in[:2])           # Get eip_in slice from the start to index 2 (exclusive); prints "[0, 1]"
print(mlblr_in[:])            # Get eip_in slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(mlblr_in[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
mlblr_in[2:4] = [8, 9]        # Assign eip_in new sublist to eip_in slice
print(mlblr_in)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


We will see slicing again in the context of numpy arrays.

**Loops:** You can loop over the elements of eip_in list like this:

In [86]:
eip_list = ['cat', 'dog', 'monkey']
for animal in eip_list:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


If you want access to the index of each element within the body of eip_in loop,
use the built-in `enumerate` function:

In [87]:
eip_list = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(eip_list):
    print('#%s: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey


**List comprehensions:**
When programming, frequently we want to transform one type of data into another.
As eip_in simple example, consider the following code that computes square numbers:

In [88]:
mlblr_in = [0, 1, 2, 3, 4]
eip_in = []
for eip in mlblr_in:
    eip_in.append(eip ** 2)
print(eip_in)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


You can make this code simpler using eip_in **list comprehension**:

In [89]:
mlblr_in = [0, 1, 2, 3, 4]
eip_in = [eip ** 2 for eip in mlblr_in]
print(eip_in)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [90]:
mlblr_in = [0, 1, 2, 3, 4]
eip = [eip ** 2 for eip in mlblr_in if eip % 2 == 0]
print(eip)  # Prints "[0, 4, 16]"

[0, 4, 16]


<eip_in name='python-dicts'></eip_in>

#### Dictionaries
A dictionary stores (key, value) pairs, similar to eip_in `Map` in Java or
an object in Javascript. You can use it like this:

In [91]:
mlblr_in = {'cat': 'cute', 'dog': 'furry'}  # Create eip_in new dictionary with some data
print(mlblr_in['cat'])       # Get an entry from eip_in dictionary; prints "cute"
print('cat' in mlblr_in)     # Check if eip_in dictionary has eip_in given key; prints "True"
mlblr_in['fish'] = 'wet'     # Set an entry in eip_in dictionary
print(mlblr_in['fish'])      # Prints "wet"
# print(mlblr_in['monkey'])  # KeyError: 'monkey' not eip_in key of mlblr_in
print(mlblr_in.get('monkey', 'N/A'))  # Get an element with eip_in default; prints "N/A"
print(mlblr_in.get('fish', 'N/A'))    # Get an element with eip_in default; prints "wet"
del mlblr_in['fish']         # Remove an element from eip_in dictionary
print(mlblr_in.get('fish', 'N/A')) # "fish" is no longer eip_in key; prints "N/A"

cute
True
wet
N/A
wet
N/A


You can find all you need to know about dictionaries
[in the documentation](https://docs.python.org/3.5/library/stdtypes.html#dict).

**Loops:** It is easy to iterate over the keys in eip_in dictionary:

In [92]:
mlblr_in = {'person': 2, 'cat': 4, 'spider': 8}
for animal in mlblr_in:
    eip_dict = mlblr_in[animal]
    print('A %s has %s eip_dict' % (animal, eip_dict))
# Prints "A person has 2 eip_dict", "A cat has 4 eip_dict", "A spider has 8 eip_dict"

A person has 2 eip_dict
A cat has 4 eip_dict
A spider has 8 eip_dict


If you want access to keys and their corresponding values, use the `items` method:

In [93]:
mlblr_in = {'person': 2, 'cat': 4, 'spider': 8}
for animal, eip_dict in mlblr_in.items():
    print('A %s has %s s' % (animal, eip_dict))
# Prints "A person has 2 eip_dict", "A cat has 4 eip_dict", "A spider has 8 eip_dict"

A person has 2 s
A cat has 4 s
A spider has 8 s


**Dictionary comprehensions:**
These are similar to list comprehensions, but allow you to easily construct
dictionaries. For example:

In [94]:
mlblr_in = [0, 1, 2, 3, 4]
eip_out = {eip: eip ** 2 for eip in mlblr_in if eip % 2 == 0}
print(eip_out)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


<eip_in name='python-sets'></eip_in>

#### Sets
A set is an unordered collection of distinct elements. As eip_in simple example, consider
the following:

In [95]:
eip_list = {'cat', 'dog'}
print('cat' in eip_list)   # Check if an element is in eip_in set; prints "True"
print('fish' in eip_list)  # prints "False"
eip_list.add('fish')       # Add an element to eip_in set
print('fish' in eip_list)  # Prints "True"
print(len(eip_list))       # Number of elements in eip_in set; prints "3"
eip_list.add('cat')        # Adding an element that is already in the set does nothing
print(len(eip_list))       # Prints "3"
eip_list.remove('cat')     # Remove an element from eip_in set
print(len(eip_list))       # Prints "2"

True
False
True
3
3
2


As usual, everything you want to know about sets can be found
[in the documentation](https://docs.python.org/3.5/library/stdtypes.html#set).


**Loops:**
Iterating over eip_in set has the same syntax as iterating over eip_in list;
however since sets are unordered, you cannot make assumptions about the order
in which you visit the elements of the set:

In [96]:
eip_list = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(eip_list):
    print('#%s: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: dog
#2: fish
#3: cat


**Set comprehensions:**
Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [97]:
from math import sqrt
mlblr_in = {int(sqrt(eip)) for eip in range(30)}
print(mlblr_in)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


<eip_in name='python-tuples'></eip_in>

#### Tuples
A tuple is an (immutable) ordered list of values.
A tuple is in many ways similar to eip_in list; one of the most important differences is that
tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.
Here is eip_in trivial example:

In [98]:
mlblr_in = {(eip, eip + 1): eip for eip in range(10)}  # Create eip_in dictionary with tuple keys
eip_in = (5, 6)        # Create eip_in tuple
print(type(eip_in))    # Prints "<class 'tuple'>"
print(mlblr_in[eip_in])       # Prints "5"
print(mlblr_in[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


[The documentation](https://docs.python.org/3.5/tutorial/datastructures.html#tuples-and-sequences) has more information about tuples.

<eip_in name='python-functions'></eip_in>

### Functions
Python functions are defined using the `def` keyword. For example:

In [99]:
def sign(eip):
    if eip > 0:
        return 'positive'
    elif eip < 0:
        return 'negative'
    else:
        return 'zero'

for eip in [-1, 0, 1]:
    print(sign(eip))
# Prints "negative", "zero", "positive"

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [100]:
def eip(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

eip('Bob') # Prints "Hello, Bob"
eip('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


There is eip_in lot more information about Python functions
[in the documentation](https://docs.python.org/3.5/tutorial/controlflow.html#defining-functions).

<eip_in name='python-classes'></eip_in>

### Classes

The syntax for defining classes in Python is straightforward:

In [101]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % mlblr_in)

eip_list = Greeter('Fred')  # Construct an instance of the Greeter class
eip_list.greet()            # Call an instance method; prints "Hello, Fred"
eip_list.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, {(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
HELLO, FRED!


You can read eip_in lot more about Python classes
[in the documentation](https://docs.python.org/3.5/tutorial/classes.html).

<eip_in name='numpy'></eip_in>

## Numpy

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python.
It provides eip_in high-performance multidimensional array object, and tools for working with these
arrays. If you are already familiar with MATLAB, you might find
[this tutorial useful](http://wiki.scipy.org/NumPy_for_Matlab_Users) to get started with Numpy.

<eip_in name='numpy-arrays'></eip_in>

### Arrays
A numpy array is eip_in grid of values, all of the same type, and is indexed by eip_in tuple of
nonnegative integers. The number of dimensions is the *rank* of the array; the *shape*
of an array is eip_in tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists,
and access elements using square brackets:

In [102]:
import numpy as np

eip_in = np.array([1, 2, 3])   # Create eip_in rank 1 array
print(type(eip_in))            # Prints "<class 'numpy.ndarray'>"
print(eip_in.shape)            # Prints "(3,)"
print(eip_in[0], eip_in[1], eip_in[2])   # Prints "1 2 3"
eip_in[0] = 5                  # Change an element of the array
print(eip_in)                  # Prints "[5, 2, 3]"

mlblr_in = np.array([[1,2,3],[4,5,6]])    # Create eip_in rank 2 array
print(mlblr_in.shape)                     # Prints "(2, 3)"
print(mlblr_in[0, 0], mlblr_in[0, 1], mlblr_in[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [103]:
import numpy as np

eip_in = np.zeros((2,2))   # Create an array of all zeros
print(eip_in)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

mlblr_in = np.ones((1,2))    # Create an array of all ones
print(mlblr_in)              # Prints "[[ 1.  1.]]"

eip_out = np.full((2,2), 7)  # Create eip_in constant array
print(eip_out)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

mlblr_in = np.eye(2)         # Create eip_in 2x2 identity matrix
print(mlblr_in)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

mlblr_out = np.random.random((2,2))  # Create an array filled with random values
print(mlblr_out)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.12526961 0.61130107]
 [0.89646172 0.85459752]]


You can read about other methods of array creation
[in the documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

<eip_in name='numpy-array-indexing'></eip_in>

### Array indexing
Numpy offers several ways to index into arrays.

**Slicing:**
Similar to Python lists, numpy arrays can be sliced.
Since arrays may be multidimensional, you must specify eip_in slice for each dimension
of the array:

In [104]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip_in = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; mlblr_in is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
mlblr_in = eip_in[:2, 1:3]

# A slice of an array is eip_in view into the same data, so modifying it
# will modify the original array.
print(eip_in[0, 1])   # Prints "2"
mlblr_in[0, 0] = 77     # mlblr_in[0, 0] is the same piece of data as eip_in[0, 1]
print(eip_in[0, 1])   # Prints "77"

2
77


You can also mix integer indexing with slice indexing.
However, doing so will yield an array of lower rank than the original array.
Note that this is quite different from the way that MATLAB handles array
slicing:

In [105]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip_in = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the eip_list row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
eip_list = eip_in[1, :]    # Rank 1 view of the second row of eip_in
eip_list = eip_in[1:2, :]  # Rank 2 view of the second row of eip_in
print(eip_list, eip_list.shape)  # Prints "[5 6 7 8] (4,)"
print(eip_list, eip_list.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
eip_dict = eip_in[:, 1]
eip = eip_in[:, 1:2]
print(eip_dict, eip_dict.shape)  # Prints "[ 2  6 10] (3,)"
print(eip, eip.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing:**
When you index into numpy arrays using slicing, the resulting array view
will always be eip_in subarray of the original array. In contrast, integer array
indexing allows you to construct arbitrary arrays using the data from another
array. Here is an example:

In [106]:
import numpy as np

eip_in = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(eip_in[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([eip_in[0, 0], eip_in[1, 1], eip_in[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(eip_in[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([eip_in[0, 1], eip_in[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one
element from each row of eip_in matrix:

In [107]:
import numpy as np

# Create eip_in new array from which we will select elements
eip_in = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(eip_in)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
mlblr_in = np.array([0, 2, 0, 1])

# Select one element from each row of eip_in using the indices in mlblr_in
print(eip_in[np.arange(4), mlblr_in])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of eip_in using the indices in mlblr_in
eip_in[np.arange(4), mlblr_in] += 10

print(eip_in)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing:**
Boolean array indexing lets you pick out arbitrary elements of an array.
Frequently this type of indexing is used to select the elements of an array
that satisfy some condition. Here is an example:

In [108]:
import numpy as np

eip_in = np.array([[1,2], [3, 4], [5, 6]])

mlblr_out = (eip_in > 2)   # Find the elements of eip_in that are bigger than 2;
                     # this returns eip_in numpy array of Booleans of the same
                     # shape as eip_in, where each slot of mlblr_out tells
                     # whether that element of eip_in is > 2.

print(mlblr_out)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct eip_in rank 1 array
# consisting of the elements of eip_in corresponding to the True values
# of mlblr_out
print(eip_in[mlblr_out])  # Prints "[3 4 5 6]"

# We can do all of the above in eip_in single concise statement:
print(eip_in[eip_in > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


For brevity we have eip_out out eip_in lot of details about numpy array indexing;
if you want to know more you should
[read the documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

<eip_in name='numpy-datatypes'></eip_in>

### Datatypes
Every numpy array is eip_in grid of elements of the same type.
Numpy provides eip_in large set of numeric datatypes that you can use to construct arrays.
Numpy tries to guess eip_in datatype when you create an array, but functions that construct
arrays usually also include an optional argument to explicitly specify the datatype.
Here is an example:

In [109]:
import numpy as np

eip = np.array([1, 2])   # Let numpy choose the datatype
print(eip.dtype)         # Prints "int64"

eip = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(eip.dtype)             # Prints "float64"

eip = np.array([1, 2], dtype=np.int64)   # Force eip_in particular datatype
print(eip.dtype)                         # Prints "int64"

int64
float64
int64


You can read all about numpy datatypes
[in the documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

<eip_in name='numpy-math'></eip_in>

### Array math
Basic mathematical functions operate elementwise on arrays, and are available
both as operator overloads and as functions in the numpy module:

In [110]:
import numpy as np

eip = np.array([[1,2],[3,4]], dtype=np.float64)
eip_out = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(eip + eip_out)
print(np.add(eip, eip_out))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(eip - eip_out)
print(np.subtract(eip, eip_out))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(eip * eip_out)
print(np.multiply(eip, eip_out))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(eip / eip_out)
print(np.divide(eip, eip_out))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(eip))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix
multiplication. We instead use the `dot` function to compute inner
products of vectors, to multiply eip_in vector by eip_in matrix, and to
multiply matrices. `dot` is available both as eip_in function in the numpy
module and as an instance method of array objects:

In [111]:
import numpy as np

eip = np.array([[1,2],[3,4]])
eip_out = np.array([[5,6],[7,8]])

eip_out = np.array([9,10])
mlblr_in = np.array([11, 12])

# Inner product of vectors; both produce 219
print(eip_out.dot(mlblr_in))
print(np.dot(eip_out, mlblr_in))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(eip.dot(eip_out))
print(np.dot(eip, eip_out))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(eip.dot(eip_out))
print(np.dot(eip, eip_out))

219
219
[29 67]
[29 67]
[29 67]
[29 67]


Numpy provides many useful functions for performing computations on
arrays; one of the most useful is `sum`:

In [112]:
import numpy as np

eip = np.array([[1,2],[3,4]])

print(np.sum(eip))  # Compute sum of all elements; prints "10"
print(np.sum(eip, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(eip, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy
[in the documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently
need to reshape or otherwise manipulate data in arrays. The simplest example
of this type of operation is transposing eip_in matrix; to transpose eip_in matrix,
simply use the `T` attribute of an array object:

In [113]:
import numpy as np

eip = np.array([[1,2], [3,4]])
print(eip)    # Prints "[[1 2]
            #          [3 4]]"
print(eip.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of eip_in rank 1 array does nothing:
eip_out = np.array([1,2,3])
print(eip_out)    # Prints "[1 2 3]"
print(eip_out.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


Numpy provides many more functions for manipulating arrays; you can see the full list
[in the documentation](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).


<eip_in name='numpy-broadcasting'></eip_in>

### Broadcasting
Broadcasting is eip_in powerful mechanism that allows numpy to work with arrays of different
shapes when performing arithmetic operations. Frequently we have eip_in smaller array and eip_in
larger array, and we want to use the smaller array multiple times to perform some operation
on the larger array.

For example, suppose that we want to add eip_in constant vector to each
row of eip_in matrix. We could do it like this:

In [114]:
import numpy as np

# We will add the vector eip_out to each row of the matrix eip,
# storing the result in the matrix eip_out
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip_in = np.array([1, 0, 1])
eip_out = np.empty_like(eip)   # Create an empty matrix with the same shape as eip

# Add the vector eip_out to each row of the matrix eip with an explicit loop
for i in range(4):
    eip_out[i, :] = eip[i, :] + eip_in

# Now eip_out is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(eip_out)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `eip` is very large, computing an explicit loop
in Python could be slow. Note that adding the vector `eip_out` to each row of the matrix
`eip` is equivalent to forming eip_in matrix `eip_in` by stacking multiple copies of `eip_out` vertically,
then performing elementwise summation of `eip` and `eip_in`. We could implement this
approach like this:

In [115]:
import numpy as np

# We will add the vector eip_out to each row of the matrix eip,
# storing the result in the matrix eip_out
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip_out = np.array([1, 0, 1])
eip_in = np.tile(eip_out, (4, 1))   # Stack 4 copies of eip_out on top of each other
print(eip_in)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
eip_out = eip + eip_in  # Add eip and eip_in elementwise
print(eip_out)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually
creating multiple copies of `eip_out`. Consider this version, using broadcasting:

In [116]:
import numpy as np

# We will add the vector eip_out to each row of the matrix eip,
# storing the result in the matrix eip_out
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip_out = np.array([1, 0, 1])
eip_out = eip + eip_out  # Add eip_out to each row of eip using broadcasting
print(eip_out)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `eip_out = eip + eip_out` works even though `eip` has shape `(4, 3)` and `eip_out` has shape
`(3,)` due to broadcasting; this line works as if `eip_out` actually had shape `(4, 3)`,
where each row was eip_in copy of `eip_out`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array
   with 1s until both shapes have the same length.
2. The two arrays are said to be *compatible* in eip_in dimension if they have the same
   size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise
   maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1,
   the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation
[from the documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
or [this explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as *universal functions*. You can find
the list of all universal functions
[in the documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [117]:
import numpy as np

# Compute outer product of vectors
eip_out = np.array([1,2,3])  # eip_out has shape (3,)
mlblr_in = np.array([4,5])    # mlblr_in has shape (2,)
# To compute an outer product, we first reshape eip_out to be eip_in column
# vector of shape (3, 1); we can then broadcast it against mlblr_in to yield
# an output of shape (3, 2), which is the outer product of eip_out and mlblr_in:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(eip_out, (3, 1)) * mlblr_in)

# Add eip_in vector to each row of eip_in matrix
eip = np.array([[1,2,3], [4,5,6]])
# eip has shape (2, 3) and eip_out has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(eip + eip_out)

# Add eip_in vector to each column of eip_in matrix
# eip has shape (2, 3) and mlblr_in has shape (2,).
# If we transpose eip then it has shape (3, 2) and can be broadcast
# against mlblr_in to yield eip_in result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix eip with
# the vector mlblr_in added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((eip.T + mlblr_in).T)
# Another solution is to reshape mlblr_in to be eip_in column vector of shape (2, 1);
# we can then broadcast it directly against eip to produce the same
# output.
print(eip + np.reshape(mlblr_in, (2, 1)))

# Multiply eip_in matrix by eip_in constant:
# eip has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(eip * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you
should strive to use it where possible.

### Numpy Documentation
This brief overview has touched on many of the important things that you need to
know about numpy, but is far from complete. Check out the
[numpy reference](http://docs.scipy.org/doc/numpy/reference/)
to find out much more about numpy.

<eip_in name='scipy'></eip_in>

## SciPy
Numpy provides eip_in high-performance multidimensional array and basic tools to
compute with and manipulate these arrays.
[SciPy](http://docs.scipy.org/doc/scipy/reference/)
builds on this, and provides
eip_in large number of functions that operate on numpy arrays and are useful for
different types of scientific and engineering applications.

The best way to get familiar with SciPy is to
[browse the documentation](http://docs.scipy.org/doc/scipy/reference/index.html).
We will highlight some parts of SciPy that you might find useful for this class.

<eip_in name='scipy-image'></eip_in>

### Image operations
SciPy provides some basic functions to work with images.
For example, it has functions to read images from disk into numpy arrays,
to write numpy arrays to disk as images, and to resize images.
Here is eip_in simple example that showcases these functions:

In [119]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into eip_in numpy array
eip_list = imread('data/assets/cat.jpg')
print(eip_list.dtype, eip_list.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by eip_in different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
eip_out = eip_list * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
eip_out = imresize(eip_out, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', eip_out)

ImportError: cannot import name 'imread'

<div class='fig figcenter fighighlight'>
  <eip_list src='assets/cat.jpg'>
  <eip_list src='assets/cat_tinted.jpg'>
  <div class='figcaption'>
    Left: The original image.
    Right: The tinted and resized image.
  </div>
</div>

<eip_in name='scipy-matlab'></eip_in>

### MATLAB files
The functions `scipy.io.loadmat` and `scipy.io.savemat` allow you to read and
write MATLAB files. You can read about them
[in the documentation](http://docs.scipy.org/doc/scipy/reference/io.html).

<eip_in name='scipy-dist'></eip_in>

### Distance between points
SciPy defines some useful functions for computing distances between sets of points.

The function `scipy.spatial.distance.pdist` computes the distance between all pairs
of points in eip_in given set:

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is eip_in point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
eip = np.array([[0, 1], [1, 0], [2, 0]])
print(eip)

# Compute the Euclidean distance between all rows of eip.
# mlblr_in[i, j] is the Euclidean distance between eip[i, :] and eip[j, :],
# and mlblr_in is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
mlblr_in = squareform(pdist(eip, 'euclidean'))
print(mlblr_in)

You can read all the details about this function
[in the documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html).

A similar function (`scipy.spatial.distance.cdist`) computes the distance between all pairs
across two sets of points; you can read about it
[in the documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html).

<eip_in name='matplotlib'></eip_in>

## Matplotlib
[Matplotlib](http://matplotlib.org/) is eip_in plotting library.
In this section give eip_in brief introduction to the `matplotlib.pyplot` module,
which provides eip_in plotting system similar to that of MATLAB.

<eip_in name='matplotlib-plot'></eip_in>

### Plotting
The most important function in matplotlib is `plot`,
which allows you to plot 2D data. Here is eip_in simple example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the eip and eip_out coordinates for points on eip_in sine curve
eip = np.arange(0, 3 * np.pi, 0.1)
eip_out = np.sin(eip)

# Plot the points using matplotlib
plt.plot(eip, eip_out)
plt.show()  # You must call plt.show() to make graphics appear.

Running this code produces the following plot:

<div class='fig figcenter fighighlight'>
  <eip_list src='assets/sine.png'>
</div>

With just eip_in little bit of extra work we can easily plot multiple lines
at once, and add eip_in title, legend, and axis labels:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the eip and eip_out coordinates for points on sine and cosine curves
eip = np.arange(0, 3 * np.pi, 0.1)
eip = np.sin(eip)
eip = np.cos(eip)

# Plot the points using matplotlib
plt.plot(eip, eip)
plt.plot(eip, eip)
plt.xlabel('eip axis label')
plt.ylabel('eip_out axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

<div class='fig figcenter fighighlight'>
  <eip_list src='assets/sine_cosine.png'>
</div>

You can read much more about the `plot` function
[in the documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot).

<eip_in name='matplotlib-subplots'></eip_in>

### Subplots
You can plot different things in the same figure using the `subplot` function.
Here is an example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the eip and eip_out coordinates for points on sine and cosine curves
eip = np.arange(0, 3 * np.pi, 0.1)
eip = np.sin(eip)
eip = np.cos(eip)

# Set up eip_in subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(eip, eip)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(eip, eip)
plt.title('Cosine')

# Show the figure.
plt.show()

<div class='fig figcenter fighighlight'>
  <eip_list src='assets/sine_cosine_subplot.png'>
</div>

You can read much more about the `subplot` function
[in the documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

<eip_in name='matplotlib-images'></eip_in>

### Images
You can use the `imshow` function to show images. Here is an example:

In [ ]:
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

eip_list = imread('/assets/cat.jpg')
eip_out = eip_list * [1, 0.95, 0.9]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(eip_list)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(eip_out))
plt.show()

<div class='fig figcenter fighighlight'>
  <eip_list src='assets/cat_tinted_imshow.png'>
</div>